### ISSUE TITLE
Latest Cafienne docker image will not run

### ISSUE THREAD

**Issue by wjgerritsen-0001** [cafienne/getting-started#13]
When starting the latest docker image (updated 19 hours ago) It will fail with the following message:

```
cafienne        | 2020-11-24 07:53:51,443|INFO  o.f.core.internal.command.DbMigrate - Successfully applied 3 migrations to schema "PUBLIC" (execution time 00:00.172s)
cafienne        | java.lang.IllegalArgumentException: Serializer identifier [52943] of [org.cafienne.akka.actor.serialization.CommandSerializer] is not unique. It is also used by [org.cafienne.akka.actor.serialization.ResponseSerializer].
cafienne        |       at akka.serialization.Serialization.$anonfun$serializerByIdentity$1(Serialization.scala:515)
cafienne        |       at scala.collection.TraversableOnce$folder$1$.apply(TraversableOnce.scala:187)
cafienne        |       at scala.collection.TraversableOnce$folder$1$.apply(TraversableOnce.scala:185)
cafienne        |       at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:370)
cafienne        |       at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:675)
cafienne        |       at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:189)
cafienne        |       at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:184)
cafienne        |       at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:108)
cafienne        |       at akka.serialization.Serialization.<init>(Serialization.scala:508)
cafienne        |       at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:18)
cafienne        |       at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:14)
cafienne        |       at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1158)
cafienne        |       at akka.actor.ActorSystemImpl.$anonfun$loadExtensions$1(ActorSystem.scala:1201)
cafienne        |       at scala.collection.Iterator.foreach(Iterator.scala:943)
cafienne        |       at scala.collection.Iterator.foreach$(Iterator.scala:943)
cafienne        |       at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
cafienne        |       at scala.collection.IterableLike.foreach(IterableLike.scala:74)
cafienne        |       at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
cafienne        |       at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
cafienne        |       at akka.actor.ActorSystemImpl.loadExtensions$1(ActorSystem.scala:1195)
cafienne        |       at akka.actor.ActorSystemImpl.loadExtensions(ActorSystem.scala:1214)
cafienne        |       at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:1035)
cafienne        |       at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:1022)
cafienne        |       at akka.actor.ActorSystemImpl._start(ActorSystem.scala:1022)
cafienne        |       at akka.actor.ActorSystemImpl.start(ActorSystem.scala:1045)
cafienne        |       at akka.actor.ActorSystem$.apply(ActorSystem.scala:272)
cafienne        |       at akka.actor.ActorSystem$.apply(ActorSystem.scala:316)
cafienne        |       at akka.actor.ActorSystem$.apply(ActorSystem.scala:260)
cafienne        |       at org.cafienne.akka.actor.CaseSystem$.start(CaseSystem.scala:71)
cafienne        |       at org.cafienne.service.Main$.startup(Main.scala:55)
cafienne        |       at org.cafienne.service.Main$.delayedEndpoint$org$cafienne$service$Main$1(Main.scala:40)
cafienne        |       at org.cafienne.service.Main$delayedInit$body.apply(Main.scala:37)
cafienne        |       at scala.Function0.apply$mcV$sp(Function0.scala:39)
cafienne        |       at scala.Function0.apply$mcV$sp$(Function0.scala:39)
cafienne        |       at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
cafienne        |       at scala.App.$anonfun$main$1$adapted(App.scala:80)
cafienne        |       at scala.collection.immutable.List.foreach(List.scala:392)
cafienne        |       at scala.App.main(App.scala:80)
cafienne        |       at scala.App.main$(App.scala:78)
cafienne        |       at org.cafienne.service.Main$.main(Main.scala:37)
cafienne        |       at org.cafienne.service.Main.main(Main.scala)
cafienne exited with code 255
```

Reproduce: 
get getting-started repo
docker-compose up

**Comment by wjgerritsen-0001** [comment]
Sorry, when I updated the getting-started local working copy, I succeeded in starting the engine.
